PPIpredDir:
TrainingLogs: 
XValOutputs: 
configFile: 
homeDir: 
modelsCheckpoints: 
output: 
outputFeaturesEngineering: 
outputGoldStandard: 
outputPredictedPPI: 
outputPredictedPPI_IDs:
outputPredictions:
outputPreprocessing:
outputPreprocessingBgee:
outputPreprocessingHPA: 
outputPreprocessingIntAct: 
outputPreprocessingMatchingUniprot:
outputPreprocessingNegatome:
outputPreprocessingPrePPI: 
outputPreprocessingString: 
outputPreprocessingUniprot: 
rawData:
rawDataBgee: 
rawDataHPA:
rawDataIntact: 
rawDataPrePPI:
rawDataString: 
rawDataUniProt: 
rdsDir: 
rdsPPIdir: 
tempDir: 
