PPIpredDir: /home/ll582/PPI_predictions
TrainingLogs: /rds/user/ll582/hpc-work/PPIdata/output/4_predictions/training_logs
XValOutputs: /rds/user/ll582/hpc-work/PPIdata/output/4_predictions/XVal
configFile: /home/ll582/PPI_predictions/config.yaml
homeDir: /home/ll582
modelsCheckpoints: /rds/user/ll582/hpc-work/PPIdata/output/4_predictions/training_logs/modelsCheckpoints
output: /rds/user/ll582/hpc-work/PPIdata/output
outputFeaturesEngineering: /rds/user/ll582/hpc-work/PPIdata/output/2_featuresEngineering
outputGoldStandard: /rds/user/ll582/hpc-work/PPIdata/output/3_goldStandard
outputPredictedPPI: /rds/user/ll582/hpc-work/PPIdata/output/4_predictions/predictedPPIs
outputPredictedPPI_IDs: /rds/user/ll582/hpc-work/PPIdata/output/4_predictions/predictedPPIs/listsIDs
outputPredictions: /rds/user/ll582/hpc-work/PPIdata/output/4_predictions
outputPreprocessing: /rds/user/ll582/hpc-work/PPIdata/output/1_preprocessing
outputPreprocessingBgee: /rds/user/ll582/hpc-work/PPIdata/output/1_preprocessing/Bgee
outputPreprocessingHPA: /rds/user/ll582/hpc-work/PPIdata/output/1_preprocessing/HumanProteinAtlas
outputPreprocessingIntAct: /rds/user/ll582/hpc-work/PPIdata/output/1_preprocessing/IntAct
outputPreprocessingMatchingUniprot: /rds/user/ll582/hpc-work/PPIdata/output/1_preprocessing/UniProt/matchingUniprot
outputPreprocessingNegatome: /rds/user/ll582/hpc-work/PPIdata/output/1_preprocessing/Negatome
outputPreprocessingPrePPI: /rds/user/ll582/hpc-work/PPIdata/output/1_preprocessing/PrePPI
outputPreprocessingString: /rds/user/ll582/hpc-work/PPIdata/output/1_preprocessing/STRING
outputPreprocessingUniprot: /rds/user/ll582/hpc-work/PPIdata/output/1_preprocessing/UniProt
rawData: /rds/user/ll582/hpc-work/PPIdata/rawData
rawDataBgee: /rds/user/ll582/hpc-work/PPIdata/rawData/Bgee
rawDataHPA: /rds/user/ll582/hpc-work/PPIdata/rawData/HumanProteinAtlas
rawDataIntact: /rds/user/ll582/hpc-work/PPIdata/rawData/IntAct
rawDataPrePPI: /rds/user/ll582/hpc-work/PPIdata/rawData/PrePPI
rawDataString: /rds/user/ll582/hpc-work/PPIdata/rawData/STRING
rawDataUniProt: /rds/user/ll582/hpc-work/PPIdata/rawData/UniProt
rdsDir: /rds/user/ll582/hpc-work
rdsPPIdir: /rds/user/ll582/hpc-work/PPIdata
tempDir: /rds/user/ll582/hpc-work/PPIdata/temp
